choco install d-link-network-assistant -y
choco install d2codingfont -y
choco install d4t-addons-accurate-music -y
choco install d4t-addons-keysncorpses -y
choco install dable -y
choco install dacia-toolbox -y
choco install dacia-media-nav-toolbox -y
choco install dagger -y
choco install dagger-cue -y
choco install dahua-web-plugin -y
choco install dankerino -y
choco install dapr -y
choco install darkoberon -y
choco install darkroom -y
choco install darksoulsmapviewer -y
choco install obs-studio-wiiplayer2-scripts -y
choco install darktable -y
choco install dart-sdk -y
choco install dartium --version 1.24.2 -y
choco install dasel -y
choco install dashcore -y
choco install dashlane -y
choco install dashlane-chrome -y
choco install datacrow -y
choco install datapixels -y
choco install admprovider -y
choco install data-saver-chrome -y
choco install visualstudio2017-workload-datascience -y
choco install visualstudio2019-workload-datascience -y
choco install visualstudio2022-workload-datascience -y
choco install visualstudio2017-workload-databuildtools -y
choco install visualstudio2019-workload-databuildtools -y
choco install visualstudio2022-workload-databuildtools -y
choco install visualstudio2017-workload-data -y
choco install visualstudio2019-workload-data -y
choco install visualstudio2022-workload-data -y
choco install databasenet -y
choco install databasenetpro -y
choco install databasemaster -y
choco install database-searcher -y
choco install search-sql-server-database -y
choco install databricks-cli -y
choco install databricks-odbcdriver -y
choco install datacleaner -y
choco install datadog-agent -y
choco install datahealthcheck -y
choco install datahelix -y
choco install dataram-ramdisk -y
choco install datastar -y
choco install datastax.community -y
choco install date-reminder -y
choco install datomic-free -y
choco install dattodrive -y
choco install davmail -y
choco install daxstudio -y
choco install sqlitebrowser -y
choco install sqlitebrowser.install -y
choco install sqlitebrowser.portable -y
choco install dbachecks -y
choco install dbatools -y
choco install dbatools-library.powershell -y
choco install dbeaver -y
choco install dbeaver-ee -y
choco install dbforge-mysql-cb -y
choco install dbforge-ora-cb -y
choco install dbforge-sql-cb -y
choco install dbforge-mysql-dc -y
choco install dbforge-ora-dc -y
choco install dbforge-pg-dc -y
choco install dbforge-sql-dc -y
choco install dbforge-mysql-dg -y
choco install dbforge-ora-dg -y
choco install dbforge-sql-dg -y
choco install dbforge-sql-dp -y
choco install dbforge-sql-devops -y
choco install dbforge-mysql-doc -y
choco install dbforge-ora-doc -y
choco install dbforge-sql-doc -y
choco install dbforge-sql-ep -y
choco install dbforge-sql-fus -y
choco install dbforge-sql-im -y
choco install dbforge-sql-mon -y
choco install dbforge-mysql-qb -y
choco install dbforge-sql-qb -y
choco install dbforge-mysql-sc -y
choco install dbforge-ora-sc -y
choco install dbforge-sql-schcmpr -y
choco install dbforge-sql-search -y
choco install dbforge-sql-sc -y
choco install dbforge-sql-cmpl -y
choco install dbforge-sql-decrypt -y
choco install dbforge-sql-tools -y
choco install dbforge-ora-studio -y
choco install dbforge-ora-studio-x86 -y
choco install dbforge-mysql-studio -y
choco install dbforge-pg-studio -y
choco install dbforge-sql-studio -y
choco install dbforge-sql-ut -y
choco install dbgate -y
choco install dbgate.install -y
choco install dbgate.portable -y
choco install dbkoda -y
choco install dbmigration -y
choco install dbsync -y
choco install db-visualizer -y
choco install dcc-unlit -y
choco install dcplusplus -y
choco install dcplusplus.portable -y
choco install dcm -y
choco install dcmtk -y
choco install dcmtktls -y
choco install dcode -y
choco install dd -y
choco install ddcpuid -y
choco install ddecmd -y
choco install ddev -y
choco install ddh -y
choco install ddhx -y
choco install dds-thumbnail-viewer -y
choco install de4dot -y
choco install deadbeef -y
choco install deadbeef.install -y
choco install deadbeef.portable -y
choco install wsl-debiangnulinux -y
choco install iceweasel -y
choco install debotnet -y
choco install debugdiagnostic -y
choco install debugdiagnostictool -y
choco install vscode-chrome-debug -y
choco install vscode-edge-debug -y
choco install vscode-firefox-debug -y
choco install vscode-java-debug -y
choco install dbgview -y
choco install decor8 -y
choco install decoration -y
choco install calibre-dedrm -y
choco install deeparmor -y
choco install deepgit -y
choco install deepl -y
choco install deepview -y
choco install deepvocal -y
choco install deepvocal-hitsuboku-kumi-chn -y
choco install deezer -y
choco install setdefaultprinter -y
choco install defaultprogramseditor -y
choco install defender-injector -y
choco install defiwallet -y
choco install deflopt -y
choco install defprof -y
choco install defraggler -y
choco install deimos-driver -y
choco install dejavufonts -y
choco install font-nerd-dejavusansmono -y
choco install delegate -y
choco install projectwise-deliverables-management -y
choco install dell-command-configure -y
choco install dell-command-monitor -y
choco install dellcommandupdate -y
choco install dellcommandupdate-uwp -y
choco install dell-system-update -y
choco install dell-omsa -y
choco install dell-platform-tags-utility -y
choco install supportassist -y
choco install dell-update -y
choco install delprof2 -y
choco install delta -y
choco install deluge -y
choco install demo.rest.service -y
choco install demohelper -y
choco install denemo -y
choco install deno -y
choco install dep -y
choco install dependencies -y
choco install dependency-scanner -y
choco install dependencywalker -y
choco install depressurizer -y
choco install designsparkpcb -y
choco install desk-drive -y
choco install deskenv -y
choco install deskpins -y
choco install deskscapes -y
choco install deskspace -y
choco install desktop-audio-streamer -y
choco install desktopconnector -y
choco install visualstudio2017-workload-nativedesktop -y
choco install visualstudio2019-workload-nativedesktop -y
choco install visualstudio2022-workload-nativedesktop -y
choco install desktopicontoggle -y
choco install desktop-notifications-for-android-chrome -y
choco install desktop-restore -y
choco install desktop-tech -y
choco install desktopinfo -y
choco install desktopok -y
choco install desktops -y
choco install desura -y
choco install die -y
choco install devaudit -y
choco install devbox-clink -y
choco install devbox-common.extension -y
choco install devbox-common -y
choco install devbox-conemu -y
choco install devbox-git -y
choco install devbox-gitsettings -y
choco install devbox-gitflow -y
choco install devbox-nano -y
choco install devbox-sed -y
choco install devbox-unzip -y
choco install devbox-wget -y
choco install devbox-vcredist2010 -y
choco install devbox-notepad2 -y
choco install devbox-p4merge -y
choco install devbox-rapidee -y
choco install devcon.portable -y
choco install devd -y
choco install devdocs-app -y
choco install deveimageoptimizerwpf -y
choco install geupd -y
choco install geupd4 -y
choco install libopencv-dev -y
choco install deveunitylicenseactivator -y
choco install devhub -y
choco install dfu-util -y
choco install dtc-msys2 -y
choco install deviceioview -y
choco install dt-agent -y
choco install dt-clientextension -y
choco install dt-console -y
choco install devmanview -y
choco install devpod -y
choco install devtoys -y
choco install dz-cli -y
choco install dewey -y
choco install dex2jar -y
choco install dexed -y
choco install dexpot -y
choco install dia -y
choco install dialang -y
choco install dialupass -y
choco install dictaphone -y
choco install dictpw -y
choco install diff-pdf -y
choco install difftastic -y
choco install diffuse -y
choco install digime -y
choco install digikam -y
choco install digimizer -y
choco install digital -y
choco install digsby -y
choco install dilay -y
choco install dingtalk -y
choco install dink-smallwood -y
choco install dipiscan -y
choco install directory-crop -y
choco install directorymonitor -y
choco install directoryopus -y
choco install dirsyncpro -y
choco install directx -y
choco install directx-sdk -y
choco install direvents -y
choco install dirsize -y
choco install flashplayerplugin-disable-updates-winconfig -y
choco install disable-hiberboot -y
choco install web-platform-disable-prompt -y
choco install git-disable-gcm -y
choco install disable-ms-msdt -y
choco install disableofficenag-winconfig -y
choco install disableofficemacros-winconfig -y
choco install skype-disable-updates-winconfig -y
choco install disable-smb-v1 -y
choco install disableuac -y
choco install disable-logon-blur -y
choco install disable-windows10-upgrade -y
choco install config-disablebeep -y
choco install disabledefender-winconfig -y
choco install windowsupdate.disableautorestart -y
choco install disablewintracking -y
choco install discord -y
choco install discord.install -y
choco install discord-canary -y
choco install discord-history-tracker -y
choco install discordchatexporter -y
choco install dcforoffice -y
choco install discotheek -y
choco install discoverj -y
choco install dar -y
choco install du -y
choco install disk-wipe -y
choco install disk2vhd -y
choco install diskcountersview -y
choco install diskdump -y
choco install diskext -y
choco install diskgenius -y
choco install diskled -y
choco install diskmarkstream -y
choco install diskmon -y
choco install disksmartview -y
choco install diskus -y
choco install diskview -y
choco install dismplusplus -y
choco install dispcalgui -y
choco install dispcalgui.install -y
choco install dispcalgui.portable -y
choco install dispensense-cli -y
choco install display-changer -y
choco install ddu -y
choco install displaycal -y
choco install displaycal.portable -y
choco install displayfusion -y
choco install displayfusion.portable -y
choco install displaylink -y
choco install displayz -y
choco install disposablefixer -y
choco install dissenter-browser -y
choco install ditto -y
choco install ditto.install -y
choco install ditto.portable -y
choco install uhe-diva -y
choco install dive -y
choco install divvy -y
choco install djv -y
choco install djvu-libre -y
choco install dllexp -y
choco install dmd -y
choco install dmde -y
choco install dmg2img -y
choco install concerteenv -y
choco install dmxcontrol2 -y
choco install dngrep -y
choco install dnncmd -y
choco install dns-benchmark -y
choco install dnsjumper -y
choco install dnsproxy -y
choco install dnsagent -y
choco install dnscontrol -y
choco install dnscontrol-cli -y
choco install stackexchange-dnscontrol -y
choco install dnscrypt-proxy -y
choco install dnsdataview -y
choco install dnspy -y
choco install dnspy-netfx -y
choco install dnspyex -y
choco install dnsquerysniffer -y
choco install do-more -y
choco install dobi -y
choco install docash-vega-driver -y
choco install docash-vega-firmware -y
choco install docbook-bundle -y
choco install docconverter -y
choco install docear.install -y
choco install docear.portable -y
choco install docfetcher -y
choco install docfx -y
choco install docfx-companion-tools -y
choco install docker-cli -y
choco install docker-compose -y
choco install docker-desktop -y
choco install docker-engine -y
choco install dip -y
choco install docker-toolbox -y
choco install docker-watch-forwarder -y
choco install docker-machine -y
choco install docker-machine-sakuracloud -y
choco install docker-machine-vmware -y
choco install docker-machine-vmwareworkstation -y
choco install doctl -y
choco install docto -y
choco install dogecoin -y
choco install dogecoin.install -y
choco install dogecoin.portable -y
choco install dogtail.devenv -y
choco install dokandiscutils -y
choco install dokany -y
choco install dokany2 -y
choco install dolphin -y
choco install dolt -y
choco install domainhostingview -y
choco install domo -y
choco install dontsleep -y
choco install dontsleep.install -y
choco install dontsleep.portable -y
choco install donkeykong -y
choco install donkeykongjr -y
choco install donyacalendar-cli -y
choco install doom2-maps-d2reload -y
choco install doom1-maps-dtwid -y
choco install doom-d64rtr -y
choco install doom4-death-foretold -y
choco install doomsday -y
choco install doomseeker -y
choco install dopamine -y
choco install dopdf -y
choco install doro.install -y
choco install dos2unix -y
choco install dosbox -y
choco install dbgl -y
choco install dosbox-x -y
choco install dotnet3.5 -y
choco install dotnet4.0 -y
choco install dotnet4.5 -y
choco install dotnet4.5.1 -y
choco install dotnet4.5.2 -y
choco install dotcover-cli -y
choco install dotdotgoose -y
choco install dotlocal -y
choco install dotmemory-unit -y
choco install dotmemory-unit.portable -y
choco install dotnet-version -y
choco install dotnet.script -y
choco install dotnetdash -y
choco install dotnetinstaller -y
choco install dotnetresourcesextract -y
choco install dotnetversiondetector -y
choco install dotultimate -y
choco install doublecmd -y
choco install doubledriver -y
choco install doublecadxt -y
choco install doulossil -y
choco install downloadapp -y
choco install download-info.extension -y
choco install downtester -y
choco install downtester.install -y
choco install downtester.portable -y
choco install doxide -y
choco install doxide.install -y
choco install doxide.portable -y
choco install doxie -y
choco install doxybook2 -y
choco install doxygen.install -y
choco install doxygen.portable -y
choco install dozzzaqueux -y
choco install drmemory -y
choco install drmemory.install -y
choco install drmemory.portable -y
choco install draft -y
choco install draftsight -y
choco install draglock -y
choco install dragondisk -y
choco install drasyl -y
choco install vscode-drawio -y
choco install drawio -y
choco install drawpile -y
choco install dreampie -y
choco install drivesnapshot -y
choco install driveletterview -y
choco install driverbooster -y
choco install drivereasyfree -y
choco install driverfusion -y
choco install drivergenius -y
choco install driver-officegate -y
choco install driverpacksolution -y
choco install rapr -y
choco install drivermax -y
choco install driverview -y
choco install drkspider -y
choco install drobo-dashboard -y
choco install droidsansmono -y
choco install droidcamclient -y
choco install droidcam-obs-plugin -y
choco install droidfonts -y
choco install dropbox -y
choco install dropbox-for-gmail-chrome -y
choco install dropboxifier -y
choco install dropit -y
choco install dropit.install -y
choco install dropit.portable -y
choco install dropkick -y
choco install dropkick.core -y
choco install drush.commandline -y
choco install ds4windows -y
choco install dsinternals-psmodule -y
choco install dspeech -y
choco install dsynchronize -y
choco install dtksneak -y
choco install dumeter -y
choco install dual-monitor-tools -y
choco install dualism -y
choco install dualiza -y
choco install dub -y
choco install ducible -y
choco install duckietv -y
choco install duf -y
choco install dug -y
choco install dukto -y
choco install textgenerator -y
choco install dumo -y
choco install dumpedid -y
choco install crawl -y
choco install duo-authentication -y
choco install duo-auth-proxy -y
choco install dupeguru -y
choco install dupeguru-me -y
choco install dupeguru-pe -y
choco install dupemerge -y
choco install duplicacy -y
choco install duplicatecleaner -y
choco install duplicatefilefinder -y
choco install duplicati -y
choco install duplicati.portable -y
choco install durandal-extensions-vs2013 -y
choco install dust -y
choco install dvassist -y
choco install dvc -y
choco install dvddecrypter -y
choco install dvdflick -y
choco install dvdflick-v2 -y
choco install passkey -y
choco install dvdstyler -y
choco install dwarf-fortress -y
choco install dwgtrueview -y
choco install dws.portable -y
choco install dxftoqet -y
choco install dxwnd -y
choco install dymo-connect -y
choco install dymo-label -y
choco install dynamorio.drmemory -y
choco install dbr -y
choco install dynare -y
choco install dynatraceagent -y
choco install dynatraceclient -y
